"""PDF report generation service for CropFolio recommendations."""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.api.v1.schemas.report import ReportRequest


def generate_report_pdf(data: ReportRequest) -> bytes:
    """Generate a single-page PDF recommendation report.

    Args:
        data: Report request with portfolio allocation and metrics.

    Returns:
        PDF file content as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
        leftMargin=25 * mm,
        rightMargin=25 * mm,
    )

    styles = getSampleStyleSheet()
    elements: list[object] = []

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.grey,
        spaceAfter=20,
    )

    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=10,
        spaceBefore=16,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontSize=11,
        spaceAfter=8,
    )

    # Title
    elements.append(Paragraph("CropFolio", title_style))
    elements.append(
        Paragraph("Crop Portfolio Recommendation Report", subtitle_style)
    )

    # Township info
    elements.append(
        Paragraph(f"Township: {data.township_name}", body_style)
    )
    season_label = "Monsoon" if data.season == "monsoon" else "Dry"
    elements.append(Paragraph(f"Season: {season_label}", body_style))
    elements.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%B %d, %Y')}",
            body_style,
        )
    )
    elements.append(Spacer(1, 12))

    # Allocation table
    elements.append(
        Paragraph("Recommended Crop Allocation", heading_style)
    )

    table_data = [["Crop", "Burmese", "Allocation"]]
    for alloc in data.allocations:
        table_data.append([
            alloc.crop_name,
            alloc.crop_name_mm,
            f"{alloc.weight_pct:.1f}%",
        ])

    table = Table(table_data, colWidths=[150, 120, 80])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1B7A4A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 10),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
        ("TOPPADDING", (0, 1), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E8E6E1")),
        ("ALIGN", (-1, 0), (-1, -1), "CENTER"),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 16))

    # Key metrics
    elements.append(Paragraph("Key Metrics", heading_style))

    income_formatted = f"{data.expected_income:,.0f} MMK/ha"
    elements.append(
        Paragraph(f"Expected Income: {income_formatted}", body_style)
    )
    elements.append(
        Paragraph(
            f"Risk Reduction: {data.risk_reduction_pct:.1f}%",
            body_style,
        )
    )
    elements.append(
        Paragraph(
            f"Catastrophic Loss Probability: "
            f"{data.prob_catastrophic_loss_monocrop:.1f}% (monocrop) vs "
            f"{data.prob_catastrophic_loss_diversified:.1f}% (diversified)",
            body_style,
        )
    )
    elements.append(Spacer(1, 20))

    # Footer note
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
    )
    elements.append(
        Paragraph(
            "Generated by CropFolio — Portfolio Theory for "
            "Climate-Resilient Farming in Myanmar",
            footer_style,
        )
    )

    doc.build(elements)
    return buffer.getvalue()
